micronaut:
  application:
    name: keyManager
datasources:
  default:
    url: '${DB_URL:`jdbc:postgresql://localhost:5432/postgres`}'
    driverClassName: org.postgresql.Driver
    username: '${DB_USER:`root`}'
    password: '${DB_PASSWORD:`root`}'
jpa.default.properties.hibernate.hbm2ddl.auto: create

cliente:
  itau: '${CLIENTE_ITAU:`http://localhost:9091/api/v1`}'
  bcb: '${CLIENTE_BCB:`http://localhost:8082/api/v1`}'