micronaut:
  application:
    name: keyManager
datasources:
  default:
    url: jdbc:mariadb://db:3306/mysql-mariadb?createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root
jpa.default.properties.hibernate.hbm2ddl.auto: create

cliente:
  itau: http://localhost:9091/api/v1
  bcb: http://localhost:8082/api/v1